extends: eslint:recommended

globals:
_: true
$: true
uuid: true
angular: true
Stripe: true
google: true

env:
es6: true
browser: true
node: true

parserOptions:
ecmaVersion: 8
sourceType: "module"

rules:
indent: [2, 4] # 4 spaces indentation
max-len: [2, 175, 4]
semi: [2, "always"]
no-multiple-empty-lines: [2, {"max": 2}]

brace-style: [2, "1tbs", { "allowSingleLine": true }]
comma-dangle: [2, "never"]
comma-style: [2, "last"]
computed-property-spacing: [2, "never"]
dot-location: [2, "property"]

one-var: [2, "never"]
prefer-const: [2]
no-bitwise: [2]
no-unused-vars: [2, { "args": "none" }]

array-bracket-spacing: [2, "never"]
space-unary-ops: [2, {"words": true, "nonwords": false}]
space-before-blocks: [2, "always"]
space-in-parens: [2, "never"]
